### ISSUE TITLE
Lighter version of MQTT-TLS?

### ISSUE THREAD

**Issue by asterix555** [hirotakaster/MQTT-TLS#3]
Hi,
the MQTT-TLS consumes still a big portion of flash. Would it be possible to use the encryption libs already included for the particle-cloud?

kind regards

**Comment by hirotakaster** [comment]
Hi @asterix555 
Now I got a about 60kbyte Photon application build in my MQTT-TLS test. Particle Cloud don't use TCP, it's only DTLS.
so If it have to use build with Particle firmware, MQTT-SN:UDP base MQTT protocol have to be used and have to build with firmware library. I think maybe this case is hard to use for developer, because please wait a new light size MQTT-TLS version.

**Comment by hirotakaster** [comment]
hi @asterix555 
Now i update latest MQTT-TLS version 0.1.3 to particle community library, this size up to 74kbyte in sample application.
![screenshot_2017-10-16 17 36 34](https://user-images.githubusercontent.com/203933/31604455-56123816-b29e-11e7-836a-dfaa002790ef.png)

**Comment by asterix555** [comment]
Hi hirotakaster-san,

thank you for your note! I tried to get rid of some legacy modules and I'm fine for now 👍 
I'll continue watching your rep and looking forward to see any updates!

Have a nice weekend!

**Comment by hirotakaster** [comment]
@asterix555 
I would close this issue:)

**Comment by asterix555** [comment]
sure, thank you!
